import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import NavbarComponent from "./(components)/Navbar";
import "./globals.css";
import Footer from "./(components)/Footer";
const roboto = Noto_Sans_Thai({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <NavbarComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
